require("plugins/onedarkpro")
require("plugins/gitsign")
require("plugins/lsp")
require("plugins/treesitter")
require("plugins/blink")
require("plugins/lualine")
require("plugins/navigator")
require("plugins/whichkey")
require("plugins/conform")
require("plugins/snacks")
require("plugins/bufferline")
require("plugins/codeaction")
require("plugins/copilot")
require("plugins/noice")
require("plugins/kulala")
require("plugins/leap")
require("plugins/yanky")

vim.keymap.set("n", "<leader>pu", "<cmd>lua vim.pack.update()<CR>", { desc = "Update plugins" })
